version: 2.1
# parameters:
#   GHA_Event:
#     type: string
#     default: ""
#   GHA_Actor:
#     type: string
#     default: ""
#   GHA_Action:
#     type: string
#     default: ""
#   GHA_Meta:
#     type: string
#     default: ""
#   GHA_Tag:
#     type: string
#     default: ""
# jobs:

#   release:
#     docker:
#       - image: cimg/base:stable
#     # working_directory: ~
#     steps:
#       - checkout
#       - run:
#           name: test
#           command: |
#             echo test
#             printenv
#       - run:
#           name: echo CIRCLE_PULL_REQUEST
#           command: echo $CIRCLE_PULL_REQUEST
#       - run:
#           name: echo CIRCLE_PULL_REQUESTS
#           command: echo $CIRCLE_PULL_REQUESTS
#       - run:
#           name: echo CIRCLE_TAG
#           command: echo $CIRCLE_TAG
#       - run:
#           name: echo GH_META
#           command: echo $GH_META
#       - run:
#           name: echo CIRCLE_BRANCH
#           command: echo $CIRCLE_BRANCH
#       - run:
#           name: echo CIRCLE_SHA1
#           command: echo $CIRCLE_SHA1
#       - run:
#           name: run git log
#           command: git log

# workflows:
#   build_and_release:
#     # when:
#       # Only run when the github action event is a release
#       # equal: [ "release", << pipeline.parameters.GHA_Event >> ]


#     jobs:
#       - release:
#           filters:
#             branches:
#               only: main

# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  say-hello:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: cimg/base:stable
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - say-hello